# Neighborhood Computations

In [984]:
import numpy as np
import igl
import meshplot

In [985]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

print(bunny_f)


print("-----------------------------------")


print(bunny_v)

[[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]
-----------------------------------
[[-0.0260146   0.112578    0.0363871 ]
 [-0.0321783   0.174119   -0.00263321]
 [-0.080718    0.152855    0.0302446 ]
 ...
 [-0.023099    0.156978   -0.00584018]
 [-0.0713101   0.15068    -0.0435721 ]
 [-0.0396435   0.152397   -0.00721968]]


In [986]:
meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [987]:
meshplot.plot(cube_v, cube_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [988]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Vertex-to-Face Relations

In [989]:
bunny_vf = igl.vertex_triangle_adjacency(bunny_f, len(bunny_f))
cube_vf = igl.vertex_triangle_adjacency(cube_f, len(cube_f))
sphere_vf = igl.vertex_triangle_adjacency(sphere_f, len(sphere_f))

# print(type(len(bunny_f)))

bunny_vf
# print("cube\n")
# cube_vf
# print("sphere\n")
# sphere_vf


(array([ 849,  850,  912, ..., 1500, 5112, 5264], dtype=int32),
 array([    0,     5,     9, ..., 20898, 20898, 20898], dtype=int32))

## Vertex-to-Vertex Relations

In [990]:
bunny_vv = igl.adjacency_list(bunny_f)
cube_vv = igl.adjacency_list(cube_f)
sphere_vv = igl.adjacency_list(sphere_f)


print(bunny_vv)
print("----------------------------------------------------")
print(cube_vv)
print("----------------------------------------------------")
print(sphere_vv)

[[3, 24, 308, 525, 542], [415, 549, 551, 596], [134, 287, 465, 497, 1308], [0, 246, 308, 510, 525, 543], [406, 1235, 1368, 1371, 1375], [792, 917, 1113, 3426, 3454, 3482], [484, 1130, 1163, 1179, 1191], [1236, 1267, 1352, 1381, 1382, 2146], [74, 1325, 1365, 1402, 1420], [280, 465, 1225, 1227, 1259], [11, 349, 451, 1319, 1524, 1537, 1565, 1671], [10, 12, 349, 1413, 1524, 1542, 1693], [11, 1542, 1693, 1724], [15, 238, 246, 266, 292, 526, 543], [156, 390, 440, 889], [13, 480, 503, 511, 526, 543], [17, 294, 324, 549, 551, 796, 1217], [16, 103, 324, 1217], [1547, 1598, 2014, 2034, 2053, 2070, 2085], [267, 343, 378, 506, 1436, 1450, 1451], [21, 34, 571, 1466, 1467, 1484, 1508], [20, 34, 56, 57, 58, 571, 594], [104, 295, 961, 1022, 1224, 1374], [350, 415, 740, 741, 1441, 1442], [0, 265, 291, 308, 542], [31, 36, 37, 38, 559, 568, 3324], [269, 337, 584, 622, 726, 771], [28, 1244, 1310, 1403, 1410, 1428], [27, 1236, 1410, 1428, 2136, 2146], [314, 1208, 1228, 1331, 1335, 1355], [43, 79, 80, 573, 

# Visualizing the Neighborhood Relations

In [991]:
print(bunny_f) # list of face indices into vertex positions

print("----------------------------------------------------")

print(bunny_v) # array of vertex positions v by 3

[[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]
----------------------------------------------------
[[-0.0260146   0.112578    0.0363871 ]
 [-0.0321783   0.174119   -0.00263321]
 [-0.080718    0.152855    0.0302446 ]
 ...
 [-0.023099    0.156978   -0.00584018]
 [-0.0713101   0.15068    -0.0435721 ]
 [-0.0396435   0.152397   -0.00721968]]


## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [992]:
def explosion(V, F):
    # V = 
    # F = 
    # triangle has 3 sides that's all connected to different faces, therefore we need 3 times the number of vertices
    # faces count don't change

    explode_v = np.array([V[face[j]] for face in F for j in range(3)]) # 2D list of x*3 by 3 of random values
    explode_f = np.array([[3*i, 3*i+1, 3*i+2] for i in range(len(F))]) # 2D list of x by 3 of random values   

    return explode_v, explode_f

expCube_v, expCube_f = explosion(cube_v, cube_f)
expSphere_v, expSphere_f = explosion(sphere_v, sphere_f)
expBunny_v, expBunny_f = explosion(bunny_v, bunny_f)



### Flat Shading

In [993]:
# idk what to do here :jerry:

normCube = igl.per_vertex_normals(expCube_v, expCube_f)

meshplot.plot(expCube_v, expCube_f, n=normCube , shading={"flat": True, "wireframe": True})


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [994]:
normBunny = igl.per_vertex_normals(expBunny_v, expBunny_f)

meshplot.plot(expBunny_v, expBunny_f, n=normBunny , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [995]:
# Sphere

normSphere = igl.per_vertex_normals(expSphere_v, expSphere_f)

meshplot.plot(expSphere_v, expSphere_f, n=normSphere , shading={"flat": True})



Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-vertex Shading

In [996]:
cube_n = igl.per_vertex_normals(cube_v, cube_f)

meshplot.plot(cube_v, cube_f, n = cube_n, shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-corner Shading

In [997]:
normCube = igl.per_corner_normals(cube_v, cube_f, 69)
meshplot.plot(expCube_v, expCube_f, n = normCube, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [998]:
# Bunny 


normBunny = igl.per_corner_normals(bunny_v, bunny_f, 69)

meshplot.plot(expBunny_v, expBunny_f, n=normBunny , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [999]:
normSphere = igl.per_corner_normals(sphere_v, sphere_f, 69)

meshplot.plot(expSphere_v, expSphere_f, n=normSphere , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Connected Components

In [1001]:
# Cup

cup_v, cup_f = igl.read_triangle_mesh("data/coffeecup.off")
# print(igl.face_components(cup_f))

meshplot.plot(cup_v, cup_f, c=igl.face_components(cup_f))



# Car
car_v, car_f = igl.read_triangle_mesh("data/car.off")
# print(igl.face_components(cup_f))

meshplot.plot(car_v, car_f, c=igl.face_components(car_f))

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-3.253649…

## A simple subdivision scheme