# Neighborhood Computations

In [1199]:
import numpy as np
import igl
import meshplot

In [1200]:
bunny_v, bunny_f = igl.read_triangle_mesh("data/bunny.off")
cube_v, cube_f = igl.read_triangle_mesh("data/cube.obj")
sphere_v, sphere_f = igl.read_triangle_mesh("data/sphere.obj")

# ?igl.read_triangle_mesh

print(bunny_f)


print("-----------------------------------")


print(bunny_v)

[[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]
-----------------------------------
[[-0.0260146   0.112578    0.0363871 ]
 [-0.0321783   0.174119   -0.00263321]
 [-0.080718    0.152855    0.0302446 ]
 ...
 [-0.023099    0.156978   -0.00584018]
 [-0.0713101   0.15068    -0.0435721 ]
 [-0.0396435   0.152397   -0.00721968]]


In [1201]:
meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [1202]:
meshplot.plot(cube_v, cube_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [1203]:
meshplot.plot(sphere_v, sphere_f, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Vertex-to-Face Relations

In [1204]:
bunny_vf = igl.vertex_triangle_adjacency(bunny_f, len(bunny_f))
cube_vf = igl.vertex_triangle_adjacency(cube_f, len(cube_f))
sphere_vf = igl.vertex_triangle_adjacency(sphere_f, len(sphere_f))

# print(type(len(bunny_f)))

# ?igl.vertex_triangle_adjacency

bunny_vf
# print("cube\n")
# cube_vf
# print("sphere\n")
# sphere_vf


(array([ 849,  850,  912, ..., 1500, 5112, 5264], dtype=int32),
 array([    0,     5,     9, ..., 20898, 20898, 20898], dtype=int32))

## Vertex-to-Vertex Relations

In [1205]:
bunny_vv = igl.adjacency_list(bunny_f)
cube_vv = igl.adjacency_list(cube_f)
sphere_vv = igl.adjacency_list(sphere_f)

print(bunny_f)

?igl.adjacency_list

# print(bunny_vv)
# print("----------------------------------------------------")
# print(cube_vv)
# print("----------------------------------------------------")
# print(sphere_vv)

[[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]


Docstring:
adjacency_list(f: array) -> handle


Constructs the graph adjacency list of a given mesh (v, f)

Parameters
----------
f : #f by dim array of fixed dimensional (e.g. triangle (#f by 3),
    tet (#f by 4), quad (#f by 4), etc...) mesh faces

Returns
-------
list of lists containing at index i the adjacent vertices of vertex i

See also
--------
adjacency_matrix

Notes
-----

Examples
--------
# Mesh in (v, f)
>>> a = mesh_adjacency_list(f)
Type:      builtin_function_or_method

# Visualizing the Neighborhood Relations

In [1206]:
print(bunny_f) # list of face indices into vertex positions

print("----------------------------------------------------")

print(bunny_v) # array of vertex positions v by 3

[[2784 2497 2027]
 [1077  225 1060]
 [ 425  450  381]
 ...
 [3086 3203 3162]
 [3086 3162 3151]
 [3086 3151 3085]]
----------------------------------------------------
[[-0.0260146   0.112578    0.0363871 ]
 [-0.0321783   0.174119   -0.00263321]
 [-0.080718    0.152855    0.0302446 ]
 ...
 [-0.023099    0.156978   -0.00584018]
 [-0.0713101   0.15068    -0.0435721 ]
 [-0.0396435   0.152397   -0.00721968]]


## Shading

Meshplot requires per vertex normals, so we need to "explode" the mesh

In [1207]:
def explosion(V, F):
    # V = 
    # F = 
    # triangle has 3 sides that's all connected to different faces, therefore we need 3 times the number of vertices
    # faces count don't change

    explode_v = np.array([V[face[j]] for face in F for j in range(3)]) # 2D list of x*3 by 3 of random values
    explode_f = np.array([[3*i, 3*i+1, 3*i+2] for i in range(len(F))]) # 2D list of x by 3 of random values   

    return explode_v, explode_f

expCube_v, expCube_f = explosion(cube_v, cube_f)
expSphere_v, expSphere_f = explosion(sphere_v, sphere_f)
expBunny_v, expBunny_f = explosion(bunny_v, bunny_f)



### Flat Shading

In [1208]:
# idk what to do here :jerry:

normCube = igl.per_vertex_normals(expCube_v, expCube_f)

meshplot.plot(expCube_v, expCube_f, n=normCube , shading={"flat": True, "wireframe": True})


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [1209]:
normBunny = igl.per_vertex_normals(expBunny_v, expBunny_f)

meshplot.plot(expBunny_v, expBunny_f, n=normBunny , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [1210]:
# Sphere

normSphere = igl.per_vertex_normals(expSphere_v, expSphere_f)

meshplot.plot(expSphere_v, expSphere_f, n=normSphere , shading={"flat": True})



Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-vertex Shading

In [1211]:
cube_n = igl.per_vertex_normals(cube_v, cube_f)

meshplot.plot(cube_v, cube_f, n = cube_n, shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

### Per-corner Shading

In [1212]:
normCube = igl.per_corner_normals(cube_v, cube_f, 69)
meshplot.plot(expCube_v, expCube_f, n = normCube, shading={"wireframe": True})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [1213]:
# Bunny 


normBunny = igl.per_corner_normals(bunny_v, bunny_f, 69)

meshplot.plot(expBunny_v, expBunny_f, n=normBunny , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-0.016860…

In [1214]:
normSphere = igl.per_corner_normals(sphere_v, sphere_f, 69)

meshplot.plot(expSphere_v, expSphere_f, n=normSphere , shading={"flat": False})

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

## Connected Components

In [1215]:
# Cup

cup_v, cup_f = igl.read_triangle_mesh("data/coffeecup.off")
# print(igl.face_components(cup_f))

meshplot.plot(cup_v, cup_f, c=igl.face_components(cup_f))



# Car
car_v, car_f = igl.read_triangle_mesh("data/car.off")
# print(igl.face_components(cup_f))

meshplot.plot(car_v, car_f, c=igl.face_components(car_f))

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-3.253649…

Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(-7.194198…

## A simple subdivision scheme

In [1216]:
V = np.array([
    [0.0, 0.0],
    [1.0, 0],
    [1, 1],
    [0, 1]
])

F = np.array([
    [0, 1, 2],
    [2, 3, 0]
])

# V, F = igl.read_triangle_mesh("data/bunny.off")

adj_list = igl.adjacency_list(F)

# print(adj_list)

# print("=============================================")

# This will produce a list where each item is a list of vertices adjacent to a vertex.
# For the example above, adj_list[0] will be [1, 2, 3], meaning vertex 0 is adjacent to vertices 1, 2, and 3.


# TT, _ = igl.triangle_triangle_adjacency(F)

# print(TT)
# print(_)

# print("=============================================")

# For the above example, TT will have two rows (one for each face). Each row will show which triangles 
# are adjacent to a given triangle.


EV, FE, EF = igl.edge_topology(V, F)

print(EV)

print("------------")

print(FE)

print("------------")

print(EF)


print("=============================================")
# EV: Edge-to-vertex list.
# FE: Face-to-edge list.
# EF: Edge-to-face list.


BC = igl.barycenter(V, F)

print(BC)
print("=============================================")


# v2 = np.concatenate([V, BC])


# print(v2)
# For the example above, BC will return the barycenter for each of the two triangles in F.

# EV, FE, EF = igl.edge_topology(BC, F)

# print(EV)

# print("------------")

# print(FE)

# print("------------")

# print(EF)

new_faces = []

num_original_vertices = len(V)
print(num_original_vertices)

num_original_faces = len(F)
print(num_original_faces)

for i in range(num_original_faces):
    # The vertex indices for the current triangle
    v1, v2, v3 = F[i]
    # print(v1, v2, v3, i)
    
    # The index of the barycenter for the current triangle in our new vertex list
    mf = num_original_vertices + i

    # Create new triangles
    new_faces.append([v1, v2, mf])  # triangle formed by v1, v2, and the midpoint
    new_faces.append([v2, v3, mf])  # triangle formed by v2, v3, and the midpoint
    new_faces.append([v3, v1, mf])  # triangle formed by v3, v1, and the midpoint



[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [2 3]]
------------
[[0 3 1]
 [4 2 1]]
------------
[[ 0 -1]
 [ 1  0]
 [-1  1]
 [ 0 -1]
 [ 1 -1]]
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]
4
2


In [1217]:
# Step 1
# Reminder for myself... face by definition contains INDICES for vertexs V. (can think about this like a dictionary pair?)


def step1(V, F):
    # print(V)
    # print(F)

    center_p = igl.barycenter(V, F)
    print(center_p)

    f_new = []                              # needs to be numpy array
    v_new = np.concatenate([V, center_p])   # needs to be numpy array


    v_len = len(V)

    f_len = len(F)
    # print(F)
    for i in range(f_len):
        # The vertex indices for the current triangle
        # Eg: 
        # F = [[0, 1, 20]]
        # v1 = 0, v2 = 1, v3 = 20
        v1, v2, v3 = F[i]
        # print(v1, v2, v3, i)
        
        # The index of the barycenter for the current triangle in our new vertex list
        # Lowkey forgot why this is...
        mf = v_len + i

        # Create new triangles
        f_new.append([v1, v2, mf])  # triangle formed by v1, v2, and the midpoint
        f_new.append([v2, v3, mf])  # triangle formed by v2, v3, and the midpoint
        f_new.append([v3, v1, mf])  # triangle formed by v3, v1, and the midpoint

    return np.array(v_new), np.array(f_new), center_p
    # Add three new faces for each face f in order by connecting m_f with edges to the original 3 vertices of the face; we call the set of this newly created faces F''. 
    # How to do this???

# print(sphere_v.shape)
# print(sphere_f.shape)

# v_n, f_n , center_p= step1(sphere_v, sphere_f)
v_n, f_n , center_p= step1(sphere_v, sphere_f)

# print(v_n)

# print(f_n)


# print(f_n.shape)
meshplot.plot(v_n, f_n, shading={"flat": True, "wireframe": True}) # image looks correct



[[ 0.13282033 -0.68283467 -0.055016  ]
 [ 0.15643867 -0.67428733 -0.086118  ]
 [ 0.10931867 -0.68283467 -0.093367  ]
 ...
 [ 0.06424533  0.69425467  0.03273467]
 [ 0.07121633  0.69425467  0.01127967]
 [ 0.07121633  0.69425467 -0.01127967]]


Renderer(camera=PerspectiveCamera(children=(DirectionalLight(color='white', intensity=0.6, position=(0.0, 0.0,…

In [1235]:
# Step 2


sig_n = 0           # Sigma function
p = 0               # new position p

# ?igl.adjacency_list


# def step2(V, F, p, sig_n):
#     # print(V, F)
#     # n = len(igl.adjacency_list(V)) # Valence = edges that a vertex touches
#     n = 1
#     a_n = (4-2*np.cos(2 * np.pi/ n))/9
#     temp = 0
#     for j, v in enumerate(F):
#         print(j)
#         print(v)

#         print("=========================")
#         n = 1
#         # n = len(adjacency_list(j)) # Valence = edges that a vertex touches
#         p1 = (1-a_n) * v
#         p2 = (a_n/n)
#         for i, vert in enumerate(v):
#             sig_n += vert

#         temp = temp + p1  + p2* sig_n
#         p = np.concatenate([temp])
#     return p
# # print(step2(V, F, n, p, sig_n))

# p = step2(V, F, p, sig_n)

# print(p)


# print(p)

# print(igl.barycenter(V, F))
# v_prime = np.concatenate([p, igl.barycenter(V, F)])

# print(v_prime)

def step2(V, F):
    sig_n = 0
    for i, v in enumerate(V):
        n = len(igl.adjacency_list(F)[i])
        a_n = (4 * 2 * np.cos(2 * np.pi/n))/9
        p = (1-a_n) * v
        for j, v2 in enumerate(v):
            sig_n += v2
        p += ((a_n/n) * sig_n)

    # print(p)
    # print("=======================")
    # print(center_p)
    v_prime = np.concatenate([[p], center_p])
    return v_prime

# def step2(V, F):
#     # 1. Calculate the barycenters for each face
#     center_p = np.mean(V[F], axis=1)

#     adjacency = igl.adjacency_list(F)  # Compute adjacency list once, not inside the loop
#     new_V = []

#     # 2. Update each vertex using the given formula
#     for i, v in enumerate(V):
#         n = len(adjacency[i])  # Valence for vertex 'v'
#         a_n = (4 - 2 * np.cos(2 * np.pi / n)) / 9
#         p = (1 - a_n) * v
#         sig_n = np.sum(V[adjacency[i]], axis=0)  # Sum over neighboring vertices
#         p += (a_n / n) * sig_n
#         new_V.append(p)

#     new_V = np.array(new_V)  # Convert the list of new vertices to a numpy array

#     # 3. Concatenate the updated vertices with the barycenters
#     v_prime = np.concatenate([new_V, center_p], axis=0)
    
#     return v_prime


print(step2(v_n, f_n))


meshplot.plot(step2(v_n, f_n), sphere_f, shading={"wireframe": True})


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)